name: deploy

on:
  push: 
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:  
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t pradyumnaquantum/gold .
          docker push pradyumnaquantum/gold

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH into EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }} 
          script: |
            ssh i ${{ secrets.EC2_SSH_PRIVATE_KEY }} ec2-user@${{ secrets.EC2_IP }}
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            # Pull the latest Docker image from Docker Hub
            docker pull pradyumnaquantum/gold

            # Stop and remove the existing Docker container (if any)
            docker stop testing-container || true
            docker rm testing-container || true
            docker container prune --force
            docker image prune --force
            docker system prune --force

            # Run the new Docker container
            docker run -d --name testing-container --env-file testing/config.env -p 8000:8000 --restart always pradyumnaquantum/gold

          
            
