name: Node.js CI + Auto Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted  # GitHub self-hosted runner on your EC2 instance

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sync code to EC2 (excluding .git and others)
        run: |
          rsync -av --delete \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='node_modules' \
            --exclude='.DS_Store' \
            $GITHUB_WORKSPACE/ /home/ubuntu/jwllery-backend/

      - name: Copy .env if needed
        run: |
          cp /home/ubuntu/envs/jwllery-backend.env /home/ubuntu/jwllery-backend/.env || echo ".env file not found, skipping..."

      - name: Install dependencies
        run: |
          cd /home/ubuntu/jwllery-backend
          npm ci --omit=dev

      - name: Build project (if applicable)
        run: |
          cd /home/ubuntu/jwllery-backend
          npm run build --if-present

      - name: Run tests (optional)
        run: |
          cd /home/ubuntu/jwllery-backend
          npm test || echo "No tests or tests failed, continuing..."

      - name: Restart PM2 process
        run: |
          cd /home/ubuntu/jwllery-backend
          pm2 reload jewellery-api || pm2 start index.js --name jewellery-api

      - name: Save PM2 process list
        run: pm2 save
