name: Node.js CI + Auto Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted  # runs on your EC2

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build (if applicable)
        run: npm run build --if-present

      - name: Run tests (if applicable)
        run: npm test || echo "No tests to run"

      - name: Copy code to ~/jewellery-api
        run: |
          rm -rf /home/ubuntu/jewellery-api/*
          cp -r $GITHUB_WORKSPACE/* /home/ubuntu/jwllery-backend/
          cp -r $GITHUB_WORKSPACE/.* /home/ubuntu/jwllery-backend/ || true

      - name: PM2 Restart
        run: |
          cd /home/ubuntu/jwllery-backend
          pm2 reload jewellery-api || pm2 start index.js --name jewellery-api
