name: Node.js CI + Auto Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted  # Your GitHub Actions runner on EC2

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sync code to EC2 (excluding .git and others)
        run: |
          rsync -av --delete \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='node_modules' \
            --exclude='.DS_Store' \
            --exclude='.env' \
            $GITHUB_WORKSPACE/ /home/ubuntu/jwllery-backend/

      - name: Copy .env if needed
        run: |
          cp /home/ubuntu/envs/jwllery-backend.env /home/ubuntu/jwllery-backend/.env || echo ".env file not found, skipping..."

      - name: Check if dependencies changed
        id: deps
        run: |
          cd /home/ubuntu/jwllery-backend

          if [ -f .package-lock.hash ]; then
            PREV_HASH=$(cat .package-lock.hash)
          else
            PREV_HASH=""
          fi

          CURR_HASH=$(sha256sum package-lock.json | awk '{ print $1 }')
          echo "Previous hash: $PREV_HASH"
          echo "Current  hash: $CURR_HASH"

          if [ "$PREV_HASH" != "$CURR_HASH" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo $CURR_HASH > .package-lock.hash
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Install dependencies if changed
        if: steps.deps.outputs.changed == 'true'
        run: |
          cd /home/ubuntu/jwllery-backend
          npm install --omit=dev

      - name: Build project (if applicable)
        run: |
          cd /home/ubuntu/jwllery-backend
          npm run build --if-present

      - name: Run tests (optional)
        run: |
          cd /home/ubuntu/jwllery-backend
          npm test || echo "No tests or tests failed, continuing..."

      - name: Restart PM2 process
        run: |
          cd /home/ubuntu/jwllery-backend
          pm2 reload jewellery-api || pm2 start index.js --name jewellery-api

      - name: Save PM2 process list
        run: pm2 save
