name: Node.js CI + Auto Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted  # means this runs on your EC2 where runner is installed

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build (if applicable)
        run: npm run build --if-present

      - name: Run tests (if applicable)
        run: npm test || echo "No tests to run"

      - name: PM2 Restart
        run: |
          pm2 reload jewellery-api || pm2 start index.js --name jewellery-api
